name: drails_sample_app
version: 0.0.1
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  drails: any
  paper_elements: '>=0.5.0 <0.6.0'
  polymer: '>=0.15.0 <0.16.0'
  sprintf: any
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points: web/index.html
