name: drails_sample_app
version: 0.0.1
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  drails: 0.1.2
  paper_elements: '>=0.6.1 <0.7.0'
  polymer: '>=0.15.4 <0.16.0'
  sprintf: any
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_point: web/index.html
- $dart2js:
   $exclude: [bin/server.dart, test/all.dart]
   $include: web/index.html_bootstrap.dart
