name: drails_sample_app
version: 0.0.1
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  drails: #0.1.3+3
    path: ../drails
  paper_elements: '^0.7.0'
  polymer: '^0.16.0'
  sprintf: any
  reflectable:
    path: ../reflectable/reflectable
dev_dependencies:
  unittest: any
transformers:
- reflectable:
    entry_points:
      - web/main.dart
- polymer:
    entry_point: web/index.html
- $dart2js:
    $exclude:
    - bin/server.dart
    - test/all.dart
